# Generated by Django 4.1.3 on 2022-11-25 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='curso',
        ),
        migrations.AlterField(
            model_name='participante',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Feminino', max_length=15),
        ),
        migrations.AddField(
            model_name='participante',
            name='curso',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='inscricao.curso'),
            preserve_default=False,
        ),
    ]
